config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('musiclibrary.urls')),
    path('user/', include('siteuser.urls')),
    path('posts/', include('posts.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'musiclibrary.views.custom_404'

posts/urls.py
from django.urls import path
from .views import create_post_view, \
                    artist_post_list_view, post_delete_view, user_post_list_view, edit_post_view,\
                    post_detail_view

urlpatterns = [
    path('createpost/', create_post_view, name='create_post'),
    path('artist/list/', artist_post_list_view, name='artist_posts_list'),
    path('<int:id>/delete/', post_delete_view, name='delete_post'),
    path('<int:id>/edit/', edit_post_view, name='edit_post'),
    path('user/<int:id>/list/', user_post_list_view, name='user_posts_list'),
    path('<int:id>/detail/', post_detail_view, name='post_detail')
]

siteuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUserModel(AbstractUser):
    def user_directory_path(instance, filename):
        return 'users/{0}/profile/{1}'.format(instance.username, filename)

    email = models.CharField(blank=False, null=False, unique=True, max_length=100,
                             help_text='Field is unique. '
                                       'You can register with this email only once')
    first_name = models.CharField(blank=False, null=False, max_length=150)
    last_name = models.CharField(blank=False, null=False, max_length=150)
    profile_img = models.ImageField(upload_to=user_directory_path,
                                    blank=True, null=True,
                                    help_text='This image will be used as your profile picture.')

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        db_table = 'users'

templates/add_album.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block page_title %}
    Add Album
{% endblock %}

{% block content %}
    <div class="container ">

        <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
            <a href="{% url 'home' %}">home</a>
            <span>/</span>
            <a href="{% url 'artist_detail' id=request.user.artist.id %}">artist</a>
            <span>/</span>
            <span class="active">add album</span>
        </div>

        <div class="row d-flex justify-content-center px-3 px-sm-0">
            <div class="form-card post-options mx-sm-0 col-12 col-sm-8 col-md-7 col-lg-4 py-4 px-4 rounded-4
                                            my-4 d-flex flex-column">
                <h2 class="mx-auto mb-3 my-md-2 d-flex gap-2"><i
                        class="bi bi-music-note-list me-2"></i><span>Add Album</span>
                </h2>
                <form action="{% url 'add_album' %}" method="post" enctype="multipart/form-data"
                      class="d-flex flex-column row-gap-1">
                    <h2></h2>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex">
                        <button type="submit"
                                class="btn mx-auto mx-lg-0 ms-lg-auto btn-primary go-back btn-md py-2 px-2">Add Album
                        </button>

                    </div>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

templates/add_song.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block page_title %}
    Add Song
{% endblock %}

{% block content %}
    <div class="container ">

        <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
            <a href="{% url 'home' %}">home</a>
            <span>/</span>
            <a href="{% url 'artist_detail' id=request.user.artist.id %}">artist</a>
            <span>/</span>
            <span class="active">add song</span>
        </div>

        <div class="row d-flex justify-content-center px-3 px-sm-0">
            <div class="form-card post-options mx-sm-0 col-12 col-sm-8 col-md-7 col-lg-5 py-4 px-4 rounded-4
                                            my-4 d-flex flex-column">
                <h2 class="mx-auto mb-3 my-md-2 d-flex gap-2"><i class="bi bi-music-note-list me-2"></i><span>Add Song</span>
                </h2>
                <form action="{% url 'add_song' %}" method="post" enctype="multipart/form-data" class="d-flex flex-column row-gap-1">
                    <h2></h2>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex">
                        <button type="submit" class="btn mx-auto mx-lg-0 ms-lg-auto btn-primary go-back btn-md py-2 px-2">Add Song
                        </button>

                    </div>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

templates/album_detail.html
{% extends 'layouts/base.html' %}

{% load my_tags %}
{% block page_title %}
    Album Detail
{% endblock %}

{% block content %}
    <div class="container album-detail d-flex flex-column">


        <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
            <a href="{% url 'all_artists' %}">all artists</a>
            <span>/</span>
            <a href="{{ album.artist.get_absolute_url }}">{{ album.artist.nickname }}</a>
            <span>/</span>
            <a href="{% url 'all_albums' id=album.artist.user.id %}" class="">all albums</a>
            <span>/</span>
            <span class="active">{{ album.title }}</span>
        </div>


        <div class="row album-detail-header p-3 mt-5 ">
            <div class="col-lg-4 col-xxl-3 d-flex align-items-center justify-content-center">


                <img src="{{ album.cover.url }}" alt="{{ album.title }}-album cover">
            </div>
            <div class="col-lg-8 mt-4 mt-lg-0 col-xxl-9 d-flex flex-column justify-content-center align-items-center align-items-lg-start">
                <span class="fs-5 ms-1 fw-light">Album</span>
                <h1 class="text-white">{{ album.title }}</h1>
                <span class="fs-5 ms-1 fw-light">
                    <a class="fw-medium text-white"
                       href="{{ album.artist.get_absolute_url }}">{{ album.artist }}</a> | {{ album.uploaded_at|date:'Y' }}</span>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'like_album' id=album.id %}" class="like_album ms-2 mt-2">
                        <i class="bi fs-1
                            {% with request.user.liked_content.albums.all as query %}
                                  {% if query %}
                                        {% if query|is_inside_query:album %}
                                                    bi-heart-fill
                                        {% else %}
                                                    bi-heart
                                        {% endif %}
                                   {% else %}
                                            bi-heart
                                  {% endif %}

                          {% endwith %}
                            "></i>
                    </a>
                {% endif %}


            </div>
        </div>
        <div class="row album-tracks mt-4">
            {% for song in album.songs_in_album.all %}
                <div class="col-12 mx-2 position-relative d-flex align-items-center" style="height: 60px">

                    <div id="audio-player-{{ song.id }}" class="audio-player">
                        <audio id="audio-{{ song.id }}" class="d-none position-relative"
                               controls>
                            <source src="{{ song.file.url }}" type="audio/mp3">
                            Your browser does not support the audio tag.
                        </audio>
                        <div class="d-none">
                            <label for="volume-control-{{ song.id }}" class="d-none text-start">Volume</label>
                            <input type="range" id="volume-control-{{ song.id }}"
                                   class="w-100 volume-control">
                        </div>

                        <button onclick="playPause('{{ song.id }}')"
                                id="play-pause-button-{{ song.id }}"
                                class="p-0 play-pause-button bi bi-play-fill">
                        </button>
                    </div>

                    <a href="{% url 'song_detail' id=song.id %}">
                        <h2 class="text-white mb-0 fs-5">
                            {{ song.title|truncatechars:'20' }}
                        </h2>
                    </a>
                    {% if request.user.is_authenticated %}
                        <div class="user-song-options ms-auto">
                            <a href="{% url 'like_song' id=song.id %}" class="like_song">
                                <i class="bi
                            {% with request.user.liked_content.songs.all as query %}
                                  {% if query %}
                                        {% if query|is_inside_query:song %}
                                                    bi-heart-fill
                                        {% else %}
                                                    bi-heart
                                        {% endif %}
                                   {% else %}
                                            bi-heart
                                  {% endif %}

                          {% endwith %}
                            "></i>
                            </a>
                            {#                                FURTHER AFTER PLAYLIST THING#}
                            {#                        <a href="{% url 'add_song' id=song.id %}" class="save_to_playlist">#}
                            {#                            <i class="bi#}

                            {#                             {% if request.user.playlists_of_user.all|is_inside_query: %}#}
                            {#                             	#}
                            {#                             {% endif %} #}
                            {#                             bi-bookmark"></i>#}
                            {#                        </a>#}
                        </div>
                    {% endif %}


                </div>
            {% empty %}
                <h1 class="text-white">No Songs Uploaded</h1>
            {% endfor %}

            <div class="col-12"></div>
        </div>
    </div>
{% endblock %}

templates/all_albums.html
{% extends 'layouts/base.html' %}

{% load my_tags %}
{% block page_title %}
    All Albums
{% endblock %}

{% block content %}
    {% for album in albums %}

        <div class="my-4 container album-detail d-flex flex-column">

            <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
                <a href="{% url 'all_artists' %}">all artists</a>
                <span>/</span>
                <a href="{{ album.artist.get_absolute_url }}">{{ album.artist.nickname }}</a>
                <span>/</span>
                <span class="active">all albums</span>
            </div>

            <div class="row album-detail-header p-3 mt-5 ">
                <div class="col-lg-4 col-xxl-3 d-flex align-items-center justify-content-center">


                    <img src="{{ album.cover.url }}" alt="{{ album.title }}-album cover">
                </div>
                <div class="col-lg-8 mt-4 mt-lg-0 col-xxl-9 d-flex flex-column justify-content-center align-items-center align-items-lg-start">
                    <span class="fs-5 ms-1 fw-light">Album</span>
                    <h1 class="text-white">{{ album.title }}</h1>
                    <span class="fs-5 ms-1 fw-light">
                    <a class="fw-medium text-white"
                       href="{{ album.artist.get_absolute_url }}">{{ album.artist }}</a> | {{ album.uploaded_at|date:'Y' }}</span>

                    {% if request.user.is_authenticated %}
                        <a href="{% url 'like_album' id=album.id %}" class="like_album ms-2 mt-2">
                            <i class="bi fs-1
                            {% with request.user.liked_content.albums.all as query %}
                                  {% if query %}
                                        {% if query|is_inside_query:album %}
                                                    bi-heart-fill
                                        {% else %}
                                                    bi-heart
                                        {% endif %}
                                   {% else %}
                                            bi-heart
                                  {% endif %}

                          {% endwith %}
                            "></i>
                        </a>
                    {% endif %}


                </div>
            </div>


            <div class="row album-tracks mt-4">
                {% for song in album.songs_in_album.all %}
                    <div class="col-12 mx-2 position-relative d-flex align-items-center" style="height: 60px">

                        <div id="audio-player-{{ song.id }}" class="audio-player">
                            <audio id="audio-{{ song.id }}" class="d-none position-relative"
                                   controls>
                                <source src="{{ song.file.url }}" type="audio/mp3">
                                Your browser does not support the audio tag.
                            </audio>
                            <div class="d-none">
                                <label for="volume-control-{{ song.id }}" class="d-none text-start">Volume</label>
                                <input type="range" id="volume-control-{{ song.id }}"
                                       class="w-100 volume-control">
                            </div>

                            <button onclick="playPause('{{ song.id }}')"
                                    id="play-pause-button-{{ song.id }}"
                                    class="p-0 play-pause-button bi bi-play-fill">
                            </button>
                        </div>

                        <a href="{% url 'song_detail' id=song.id %}">
                            <h2 class="text-white mb-0 fs-5">
                                {{ song.title|truncatechars:'20' }}
                            </h2>
                        </a>
                        {% if request.user.is_authenticated %}

                            <div class="user-song-options ms-auto">
                                <a href="{% url 'like_song' id=song.id %}" class="like_song">
                                    <i class="bi
                            {% with request.user.liked_content.songs.all as query %}
                                  {% if query %}
                                        {% if query|is_inside_query:song %}
                                                    bi-heart-fill
                                        {% else %}
                                                    bi-heart
                                        {% endif %}
                                   {% else %}
                                            bi-heart
                                  {% endif %}

                          {% endwith %}
                            "></i>
                                </a>
                                {#                                FURTHER AFTER PLAYLIST THING#}
                                {#                        <a href="{% url 'add_song' id=song.id %}" class="save_to_playlist">#}
                                {#                            <i class="bi#}

                                {#                             {% if request.user.playlists_of_user.all|is_inside_query: %}#}
                                {#                             	#}
                                {#                             {% endif %} #}
                                {#                             bi-bookmark"></i>#}
                                {#                        </a>#}
                            </div>

                        {% endif %}


                    </div>
                {% empty %}
                    <div class="col-12 d-flex">
                        <h2 class="mx-auto text-white fs-4">No Single Uploaded</h2>
                    </div>
                {% endfor %}

                <div class="col-12"></div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/artist_posts_list.html
{% extends 'layouts/base.html' %}

{% block page_title %}
    My Posts
{% endblock %}

{% block content %}
    <div class="container">
        {% if posts %}
            {% with posts|random as my_post %}

                <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
                    <a href="{% url 'all_artists' %}">all artists</a>
                    <span>/</span>
                    <a href="{{ my_post.artist.get_absolute_url }}">{{ my_post.artist }}</a>
                    <span>/</span>
                    <span class="active">my posts</span>
                </div>
            {% endwith %}
        {% endif %}
        <div class="row">
            <h1 class="text-center articles-section-header">My Posts</h1>
            <div class="row artist-articles row-gap-2">
                {% for post in posts %}
                    <div class="col-12 col-sm-6 col-lg-4 p-2 p-md-3 position-relative">
                        <i class="editor-gem position-absolute bi bi-gem
                                    {% if request.user.artist == post.artist %}
                                    	d-block
                                    {% else %}
                                        d-none
                                    {% endif %}
                                "></i>
                        <div class="artist-post only py-4 px-4 mx-1 position-relative d-flex flex-column">
                            <h2>{{ post.title|default:'untitled'|title|truncatechars:'18' }}</h2>
                            <span class="fs-6 my-1">{{ post.created_at|date:'F j, Y' }}</span>

                            <span>by <a href="{{ post.artist.get_absolute_url }}"
                                        class="fw-bold ms-1">{{ post.artist.nickname }}</a></span>
                            <hr class="border-2 my-1 opacity-75">
                            <p class="h-auto overflow-hidden">{{ post.text|capfirst|safe|truncatechars:'130' }}</p>
                            <div class="post-options d-flex gap-3 mb-4 mt-auto">
                                <a href="{% url 'post_detail' id=post.id %}"
                                   class="btn btn-primary  d-flex gap-2">
                                    <span class="btn-text">Read</span><i class="bi bi-arrow-right"></i>
                                </a>
                                <a href="{% url 'edit_post' id=post.id %}"
                                   class="btn btn-primary d-flex gap-2 go-back">
                                    <span class="">Edit</span><i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'delete_post' id=post.id %}"
                                   class="btn btn-outline-danger  d-flex gap-2">
                                    <span class="">Delete</span><i class="bi bi-trash"></i>
                                </a>
                            </div>


                        </div>
                    </div>
                {% empty %}
                    <h1 class="mt-5 text-center text-white">No Posts Yet</h1>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/artist_registration.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block page_title %}
    Register Artist
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="col-12 mt-5 col-md-6 col-lg-5 mx-auto form-card post-options">
            {% if is_artist %}
                <div class="alert alert-danger" role="alert">
                    Artist already exists
                </div>
            {% else %}
                <form action="{% url 'artist_register' %}" method="post" class="p-3">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-12 col-sm-6">
                            <label for="username">Username</label>
                            <input type="text" class="form-control mt-2" disabled
                                   value="{{ request.user.username }}" id="username">
                        </div>
                        <div class="col-12 col-sm-6">
                            <label for="email">Email</label>
                            <input type="text" id="email" class="form-control mt-2" disabled
                                   value="{{ request.user.email }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <label for="id_email" class="form-label">{{ form.nickname.label }}<span
                                        class="asteriskField">*</span></label>
                                {{ form.nickname }}
                                <div id="emailHelp"
                                     class="form-text text-white">{{ form.nickname.help_text }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <label for="id_email" class="form-label">{{ form.description.label }}<span
                                        class="asteriskField">*</span></label>
                                {{ form.description }}
                                <div id="emailHelp"
                                     class="form-text text-white">{{ form.description.help_text }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary go-back py-2 px-2">Create Artist</button>
                </form>
            {% endif %}

        </div>

    </div>

{% endblock %}

templates/login.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block page_title %}
    Log In
{% endblock %}

{% block content %}
    <div class="container ">
        <div class="row d-flex justify-content-center px-3 px-sm-0">
            <div class="form-card post-options mx-sm-0 col-12 col-sm-8 col-md-7 col-lg-4 py-4 px-4 rounded-4
                                            my-4 d-flex flex-column">
                <h2 class="mx-auto mb-3 my-md-2 d-flex gap-2"><i class="bi bi-music-note-list me-2"></i><span>Log In</span>
                </h2>
                <form action="{% url 'login' %}" method="post" class="d-flex flex-column row-gap-1">
                    <h2></h2>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex">
                        <button type="submit" class="btn mx-auto mx-lg-0 ms-lg-auto btn-primary go-back btn-md py-2 px-2">Log In
                        </button>

                    </div>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

templates/post_detail.html
{% extends 'layouts/base.html' %}
{#{% load template_tags %}#}
{% block page_title %}
    Post | {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">


        <div class="text-white my-breadcrumb position-relative z-2 pt-5 mb-4">
            <a href="{{ post.artist.get_absolute_url }}">{{ post.artist.nickname }}</a>
            <span>/</span>
            <a href="{% url 'user_posts_list' id=post.artist.user.id %}">all posts</a>
            <span>/</span>
            <span class="active">{{ post.title|truncatechars:'15'}}</span>
        </div>

        <div class="row artist-articles row-gap-2">
            <div class="col-12 p-2 p-md-3 position-relative">
                <i class="editor-gem fs-1 position-absolute bi bi-gem
                        {% if request.user.artist == post.artist %}
                            d-block
                        {% else %}
                            d-none
                        {% endif %}
                    "></i>
                <div class="artist-post post-detail py-4 px-4 mx-1 position-relative d-flex flex-column">
                    <h1 class="text-center articles-section-header">{{ post.title|title }}</h1>
                    <p class="mb-1 detail_date">-Published at <span
                            class="ms-1 text-white">{{ post.created_at|date:'F j, Y' }}</span></p>
                    <p class="detail_author">-Written by <a href="{{ post.artist.get_absolute_url }}"
                                                            class="ms-1 text-white">{{ post.artist.nickname }}</a></p>
                    {#                    <hr class="border-2 my-1 opacity-75">#}
                    <p class="h-auto overflow-hidden">{{ post.text|capfirst|safe }}</p>
                    <div class="post-options mb-2 mt-auto d-flex justify-content-start">

                    </div>

                </div>
            </div>
            <div class="col-12 col-lg-4 p-2 p-md-3 position-relative d-flex justify-content-center justify-content-sm-start align-items-center see-more-posts">
                {#                <div class="py-4 px-4 mx-1">#}
                {#                    <a href="{% url 'user_posts_list' id= %}"#}
                {#                       class="btn btn-primary px-3 gap-1 d-flex justify-content-center"><span>All Posts</span><i#}
                {#                            class="bi bi-arrow-right"></i></a>#}
                {#                </div>#}

            </div>
        </div>
{% endblock %}

templates/universal_error.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block page_title %}
    Error
{% endblock %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center " style="height: 400px">
        <h1 class="error-message text-center">{{ error|upper }}</h1>
    </div>
{% endblock %}

templates/user_registration.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% block page_title %}
    Registration
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center px-3 px-sm-0">
            <div class="form-card post-options col-12 col-md-7 col-lg-5 py-3 px-4 rounded-4
                                            my-4 d-flex flex-column">
                <h2 class="mx-auto mb-3 mb-md-5 d-flex gap-2"><i class="bi bi-music-note-list me-2"></i><span>Registration</span>
                </h2>
                <form action="{% url 'user_registration' %}" method="post" enctype="multipart/form-data"
                      class="d-flex flex-column row-gap-1">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-lg-6">{{ form.first_name|as_crispy_field }}</div>
                        <div class="col-12 col-lg-6">{{ form.last_name|as_crispy_field }}</div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mb-3">
                                <label for="id_username" class="form-label">{{ form.username.label }}<span
                                        class="asteriskField">*</span></label>
                                {{ form.username }}
                                <div id="emailHelp"
                                     class="form-text text-white">{{ form.username.help_text }}
                                </div>
                            </div>
                        </div>
                        <div class="col-12">

                            <div class="mb-3">
                                <label for="id_email" class="form-label">{{ form.email.label }}<span
                                        class="asteriskField">*</span></label>
                                {{ form.email }}
                                <div id="emailHelp"
                                     class="form-text text-white">{{ form.email.help_text }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-xl-8">
                            <div class="mb-3">
                                <label for="id_profile_img" class="form-label">{{ form.profile_img.label }}</label>
                                {{ form.profile_img }}
                                <div id="emailHelp"
                                     class="form-text text-white">{{ form.profile_img.help_text }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-12 col-xl-6">
                            <label for="id_password" class="form-label">{{ form.password.label }}<span
                                    class="asteriskField">*</span></label>
                            <div class="password-container position-relative">
                                {{ form.password }}
                                <i class="bi bi-eye-slash-fill toggle-password position-absolute" id="toggle-cp-id"></i>

                            </div>

                            <div id="passwordHelp"
                                 class="form-text text-white position-relative">
                                {{ form.password.help_text }}

                            </div>
                        </div>

                        <div class="col-12 col-xl-6 position-relative" id="confirm-wrapper">
                            <i class="bi bi-eye-slash-fill toggle-confirm-password position-absolute"></i>

                            {{ form.confirm_password|as_crispy_field }}

                        </div>
                        <div class="d-flex justify-content-center justify-content-lg-end">
                            <button type="submit" class="btn btn-primary go-back py-2 px-2">Register</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>


{% endblock %}